version: '3'

services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-sock
    restart: always

  reverse-proxy:
    image: traefik:v2.4
    depends_on:
      - docker-proxy
    command:
      # - "--api.insecure=true" # for debug interface on 8080
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/configs/"
      - "--entrypoints.rsync.address=:873"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web-secure.address=:443"
      - "--certificatesResolvers.le.acme.email=david.macek.0@gmail.com"
      - "--certificatesResolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.le.acme.keyType=EC256"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "873:873"
      # - "8080:8080" # for debug interface on 8080
    volumes:
      - ./reverse-proxy/traefik-tls.yml:/configs/traefik-tls.yml:ro
      - letsencrypt:/letsencrypt/
    networks:
      - default
      - docker-sock
    restart: always

  stats:
    build: ./stats
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.stats-strip.stripprefix.prefixes=/stats"
      - "traefik.http.middlewares.stats-slash-redir.redirectregex.regex=^http(s?)://([^/]*)/stats($$|[?].*)"
      - "traefik.http.middlewares.stats-slash-redir.redirectregex.replacement=http$${1}://$${2}/stats/$${3}"
      - "traefik.http.middlewares.stats-scheme-redir.redirectscheme.scheme=https"
      # http
      - "traefik.http.routers.stats.rule=Host(`repo.msys2.org`) && (Path(`/stats`) || PathPrefix(`/stats/`))"
      - "traefik.http.routers.stats.middlewares=stats-scheme-redir,stats-slash-redir,stats-strip"
      - "traefik.http.routers.stats.entrypoints=web"
      # https
      - "traefik.http.routers.stats-secure.rule=Host(`repo.msys2.org`) && (Path(`/stats`) || PathPrefix(`/stats/`))"
      - "traefik.http.routers.stats-secure.tls=true"
      - "traefik.http.routers.stats-secure.tls.certresolver=le"
      - "traefik.http.routers.stats-secure.middlewares=stats-slash-redir,stats-strip"
      - "traefik.http.routers.stats-secure.entrypoints=web-secure"
    volumes:
      - /var/lib/vnstat/:/var/lib/vnstat/:ro
      - /usr/bin/vnstat:/usr/bin/vnstat:ro
    restart: always

  packages:
    build: https://github.com/msys2/msys2-web.git
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.packages-compress.compress=true"
      - "traefik.http.middlewares.packages-scheme-redir.redirectscheme.scheme=https"
      - "traefik.http.middlewares.packages-headers.headers.stsseconds=31536000"
      # http
      - "traefik.http.routers.packages.rule=Host(`packages.msys2.org`)"
      - "traefik.http.routers.packages.middlewares=packages-scheme-redir,packages-compress"
      - "traefik.http.routers.packages.entrypoints=web"
      # https
      - "traefik.http.routers.packages-secure.rule=Host(`packages.msys2.org`)"
      - "traefik.http.routers.packages-secure.tls=true"
      - "traefik.http.routers.packages-secure.tls.certresolver=le"
      - "traefik.http.routers.packages-secure.middlewares=packages-headers,packages-compress"
      - "traefik.http.routers.packages-secure.entrypoints=web-secure"
    environment:
      - FORWARDED_ALLOW_IPS=*
    restart: always

  redir:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.homepage-redir.redirectregex.regex=^http(s?)://(?:www[.])?msys2[.](?:org|com|net)/(.*)$$"
      - "traefik.http.middlewares.homepage-redir.redirectregex.replacement=http$${1}://www.msys2.org/$${2}"
      # http
      - "traefik.http.routers.homepage.rule=Host(`msys2.org`, `msys2.com`, `www.msys2.com`, `msys2.net`, `www.msys2.net`)"
      - "traefik.http.routers.homepage.middlewares=homepage-redir"
      - "traefik.http.routers.homepage.entrypoints=web"
      # https
      - "traefik.http.routers.homepage-secure.rule=Host(`msys2.org`, `msys2.com`, `www.msys2.com`, `msys2.net`, `www.msys2.net`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.tls.certresolver=le"
      - "traefik.http.routers.homepage-secure.middlewares=homepage-redir"
      - "traefik.http.routers.homepage-secure.entrypoints=web-secure"
    restart: always

  repo:
    image: nginx
    volumes:
      - /srv/msys2repo/:/usr/share/nginx/html/:ro
      - ./repo/nginx.conf:/etc/nginx/conf.d/repo.conf:ro
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.repo.rule=Host(`repo.msys2.org`)"
      - "traefik.http.routers.repo.entrypoints=web"
      # https
      - "traefik.http.routers.repo-secure.rule=Host(`repo.msys2.org`)"
      - "traefik.http.routers.repo-secure.tls=true"
      - "traefik.http.routers.repo-secure.tls.certresolver=le"
      - "traefik.http.routers.repo-secure.entrypoints=web-secure"
    restart: always

  staging:
    build: ./staging/
    volumes:
      - staging-gnupg:/root/.gnupg/
      - staging-repos:/srv/msys2staging/
    env_file:
      - ./github_token.env
    restart: always

  stagingrepo:
    image: nginx
    volumes:
      - staging-repos:/usr/share/nginx/html/:ro
      - ./repo/nginx.conf:/etc/nginx/conf.d/repo.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.staging-strip.stripprefix.prefixes=/staging"
      - "traefik.http.middlewares.staging-slash-redir.redirectregex.regex=^http(s?)://([^/]*)/staging($$|[?].*)"
      - "traefik.http.middlewares.staging-slash-redir.redirectregex.replacement=http$${1}://$${2}/staging/$${3}"
      - "traefik.http.middlewares.staging-scheme-redir.redirectscheme.scheme=https"
      # http
      - "traefik.http.routers.staging.rule=Host(`repo.msys2.org`) && (Path(`/staging`) || PathPrefix(`/staging/`))"
      - "traefik.http.routers.staging.middlewares=staging-scheme-redir,staging-slash-redir,staging-strip"
      - "traefik.http.routers.staging.entrypoints=web"
      # https
      - "traefik.http.routers.staging-secure.rule=Host(`repo.msys2.org`) && (Path(`/staging`) || PathPrefix(`/staging/`))"
      - "traefik.http.routers.staging-secure.tls=true"
      - "traefik.http.routers.staging-secure.tls.certresolver=le"
      - "traefik.http.routers.staging-secure.middlewares=staging-slash-redir,staging-strip"
      - "traefik.http.routers.staging-secure.entrypoints=web-secure"
    restart: always

  rsync:
    build: ./rsync/
    volumes:
      - /srv/msys2repo/:/rsync-volume/:ro
      - ./rsync/rsyncd.conf:/etc/rsyncd.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.rsync.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.rsync.entrypoints=rsync"
    restart: always

volumes:
  letsencrypt:
  staging-gnupg:
  staging-repos:

networks:
  default:
  docker-sock:
    internal: true
