version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      # - "--api.insecure=true" # for debug interface on 8080
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/configs/"
      - "--entrypoints.rsync.address=:873"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web-secure.address=:443"
      - "--certificatesResolvers.le.acme.email=david.macek.0@gmail.com"
      - "--certificatesResolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "873:873"
      # - "8080:8080" # for debug interface on 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reverse-proxy/traefik-tls.yml:/configs/traefik-tls.yml:ro
      - letsencrypt:/letsencrypt
    restart: always

  packages:
    build: https://github.com/msys2/msys2-web.git
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.middlewares.pkgs-redir.redirectscheme.scheme=https"
      - "traefik.http.routers.pkgs.rule=Host(`packages.msys2.org`)"
      - "traefik.http.routers.pkgs.entrypoints=web"
      - "traefik.http.routers.pkgs.middlewares=pkgs-redir"
      # https
      - "traefik.http.routers.pkgssecure.rule=Host(`packages.msys2.org`)"
      - "traefik.http.routers.pkgssecure.tls=true"
      - "traefik.http.routers.pkgssecure.tls.certresolver=le"
      - "traefik.http.routers.pkgssecure.entrypoints=web-secure"
    environment:
      - FORWARDED_ALLOW_IPS=*
    restart: always

  redir:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.msys2-redir.redirectregex.regex=^http(s?)://(?:www[.])?msys2[.](?:org|com|net)/(.*)$$"
      - "traefik.http.middlewares.msys2-redir.redirectregex.replacement=http$${1}://www.msys2.org/$${2}"
      # http
      - "traefik.http.routers.main.rule=Host(`msys2.org`, `msys2.com`, `www.msys2.com`, `msys2.net`, `www.msys2.net`)"
      - "traefik.http.routers.main.entrypoints=web"
      - "traefik.http.routers.main.middlewares=msys2-redir"
      # https
      - "traefik.http.routers.main-secure.rule=Host(`msys2.org`, `msys2.com`, `www.msys2.com`, `msys2.net`, `www.msys2.net`)"
      - "traefik.http.routers.main-secure.tls=true"
      - "traefik.http.routers.main-secure.tls.certresolver=le"
      - "traefik.http.routers.main-secure.entrypoints=web-secure"
      - "traefik.http.routers.main-secure.middlewares=msys2-redir"
    restart: always

  repo:
    image: nginx
    volumes:
      - /srv/msys2repo:/usr/share/nginx/html:ro
      - ./repo/nginx.conf:/etc/nginx/conf.d/repo.conf:ro
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.repo.rule=Host(`repo.msys2.org`)"
      - "traefik.http.routers.repo.entrypoints=web"
      # https
      - "traefik.http.routers.repo-secure.rule=Host(`repo.msys2.org`)"
      - "traefik.http.routers.repo-secure.tls=true"
      - "traefik.http.routers.repo-secure.tls.certresolver=le"
      - "traefik.http.routers.repo-secure.entrypoints=web-secure"
    restart: always

  staging:
    build: ./staging
    volumes:
      - staging-gnupg:/root/.gnupg
      - staging-repos:/srv/msys2staging
    env_file:
      - ./github_token.env
    restart: always

  stagingrepo:
    image: nginx
    volumes:
      - staging-repos:/usr/share/nginx/html:ro
      - ./repo/nginx.conf:/etc/nginx/conf.d/repo.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-staging.stripprefix.prefixes=/staging"
      # http
      - "traefik.http.routers.staging.rule=Host(`repo.msys2.org`) && PathPrefix(`/staging/`)"
      - "traefik.http.routers.staging.middlewares=strip-staging"
      - "traefik.http.routers.staging.entrypoints=web"
      # https
      - "traefik.http.routers.staging-secure.rule=Host(`repo.msys2.org`) && PathPrefix(`/staging/`)"
      - "traefik.http.routers.staging-secure.tls=true"
      - "traefik.http.routers.staging-secure.tls.certresolver=le"
      - "traefik.http.routers.staging-secure.middlewares=strip-staging"
      - "traefik.http.routers.staging-secure.entrypoints=web-secure"
    restart: always

  rsync:
    build: ./rsync
    volumes:
      - /srv/msys2repo:/rsync-volume:ro
      - ./rsync/rsyncd.conf:/etc/rsyncd.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.rsync.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.rsync.entrypoints=rsync"
    restart: always

volumes:
  letsencrypt:
  staging-gnupg:
  staging-repos:
