[discord.msys2]
Token=""
Server="792780131906617355"
RemoteNickFormat="<{NICK}> "
AutoWebhooks=true

[matrix.msys2]
Server="https://matrix.org"
Login="minivox"
Password=""
RemoteNickFormat="<{NICK}> "
NoHomeServerSuffix=false

[irc.oftc]
Server="irc.oftc.net:6697"
Nick="msys2-on-discord"
NickServNick="nickserv"
NickServPassword=""
UseTLS=true
SkipTLSVerify=false
RemoteNickFormat="<{NICK}> "
IgnoreNicks="minifox"

[[gateway]]
name="gitter-msys2"
enable=true

[[gateway.inout]]
account="discord.msys2"
channel="gitter-msys2"

[[gateway.inout]]
account="matrix.msys2"
channel="#msys2_msys2:gitter.im"

[[gateway]]
name="oftc-msys2"
enable=true

[[gateway.inout]]
account="discord.msys2"
channel="irc-msys2"

[[gateway.inout]]
account="irc.oftc"
channel="#msys2"

[[gateway]]
name="oftc-mingw-w64"
enable=true

[[gateway.inout]]
account="discord.msys2"
channel="irc-mingw-w64"

[[gateway.inout]]
account="irc.oftc"
channel="#mingw-w64"
